In [1]:
import pandas as pd
import numpy as np
import glob

In [4]:
fn_lst = glob.glob(r'C:\Users\Josh\Documents\GitHub\sabatinilab-glm\sglm\data\raw\fig6\*')
glm_sig = [pd.read_csv(_) for _ in fn_lst]

In [5]:
for gs in glm_sig:
    display(gs)

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,1.403724,0,2.335278,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,3.251720,0,3.412341,0,0,0,0,0,0,0,0,1,0,0,1,0,1
2,2.969236,0,2.806408,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,3.014074,0,2.574419,0,0,0,0,0,0,0,0,1,0,0,1,0,1
4,3.438815,0,2.225651,0,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33605,-1.907796,0,0.329420,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33606,0.673675,0,0.226394,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33607,-0.239678,0,0.602806,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33608,0.989029,0,0.311061,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33609,0.410010,0,0.222090,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,0.356976,0,1.901955,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1.348290,0,1.600157,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2.304263,0,1.558472,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1.676598,0,2.424307,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1.141161,0,2.129839,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28956,-1.254311,0,-0.224972,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28957,-1.107998,0,-0.451930,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28958,-0.327136,0,-0.153548,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28959,-1.182926,0,-0.424418,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28960,-1.942769,0,-0.418196,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,0.612965,0,0.164935,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0.768400,0,-0.886796,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1.119193,0,0.065265,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,-0.175306,0,-0.042737,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0.864250,0,0.902455,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32345,0.418224,0,-0.543769,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32346,0.208786,0,-0.151162,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32347,-0.134053,0,-0.622494,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32348,-0.181891,0,-0.663996,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32349,-0.342978,0,-0.238752,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,1.548583,0,0.520195,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,1.157211,0,2.006076,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,-0.153376,0,1.620738,0,0,0,0,0,0,0,0,1,0,0,1,0,1
3,1.199551,0,2.883797,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,1.925334,0,3.083140,0,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35401,0.284550,0,-0.294528,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35402,0.148982,0,0.079573,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35403,0.493312,0,0.450898,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35404,1.379177,0,0.084131,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35405,0.552345,0,-0.687041,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,1.584297,0,1.171317,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1.950731,0,1.128127,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2.431726,0,1.108826,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1.952416,0,0.984731,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1.425850,0,1.059702,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44438,1.827873,0,0.124657,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44439,1.900260,0,-0.006806,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44440,0.621446,0,-0.980844,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44441,1.340885,0,-0.150772,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44442,1.923864,0,0.249289,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,1.083832,0,0.353464,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1.976794,0,0.947812,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0.913103,0,2.078647,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1.636139,0,3.194101,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0.897000,0,3.066965,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44438,-2.396440,0,-1.698253,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44439,-2.406744,0,-2.641224,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44440,-1.552914,0,-1.625296,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44441,-1.070792,0,-1.812141,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44442,-0.637815,0,-1.589821,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,0.101157,0,-0.254191,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,-0.754069,0,0.028714,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,-0.463275,0,0.726221,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,-0.789836,0,0.981874,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,-1.028920,0,0.805237,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44438,-0.297765,0,-0.156842,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44439,0.903010,0,-0.165717,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44440,1.096513,0,-1.433731,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44441,1.164428,0,-0.315971,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44442,0.866702,0,-0.003708,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Ch1,Ch2,Ch5,Ch6,centerOcc,centerIn,centerOut,rightOcc,rightIn,rightOut,rightLick,leftOcc,leftIn,leftOut,leftLick,reward,noreward
0,-0.638760,0,-1.003227,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,-0.036815,0,0.370216,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0.504867,0,1.123889,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,-0.061904,0,0.113833,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,-0.078431,0,-0.275108,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35382,0.559701,0,1.343201,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35383,1.190156,0,0.487921,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35384,0.180700,0,-0.730227,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35385,0.983466,0,1.644491,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35386,0.531205,0,0.124432,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,0,1,0.95,0.05,0,NaN
1,0,0,0,0,0,0,1,0,0.95,0.05,1,aB
2,0,0,0,0,0,0,0,1,0.95,0.05,0,Ab
3,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
4,0,0,0,0,0,0,1,0,0.95,0.05,0,ab
...,...,...,...,...,...,...,...,...,...,...,...,...
269,1,33125,33127,33151,33156,33154,0,1,0.05,0.95,0,Aa
270,1,33303,33308,33334,33358,33337,0,1,0.05,0.95,1,aA
271,1,33403,33404,33427,33451,33430,0,1,0.05,0.95,1,AA
272,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
273,0,0,0,0,0,0,0,1,0.05,0.95,0,Aa

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,0,1,0.95,0.05,0,NaN
1,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
2,0,0,0,0,0,0,1,0,0.95,0.05,1,aB
3,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
4,0,0,0,0,0,0,1,0,0.95,0.05,0,Aa
...,...,...,...,...,...,...,...,...,...,...,...,...
292,1,28677,28677,28707,28740,28710,0,1,0.05,0.95,1,AA
293,1,28763,28765,28782,28824,28784,0,1,0.05,0.95,1,AA
294,0,0,0,0,0,0,0,1,0.95,0.05,0,Aa
295,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
296,0,0,0,0,0,0,1,0,0.95,0.05,1,aB

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,1,0,0.95,0.05,1,NaN
1,0,0,0,0,0,0,0,1,0.95,0.05,0,Ab
2,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
3,0,0,0,0,0,0,1,0,0.95,0.05,1,aB
4,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
...,...,...,...,...,...,...,...,...,...,...,...,...
274,1,31322,31323,31346,31368,31349,0,1,0.05,0.95,1,aB
275,1,31399,31400,31428,31517,31430,0,1,0.05,0.95,1,AA
276,1,31898,31899,31930,31960,31935,0,1,0.05,0.95,1,AA
277,1,32142,32142,32161,32191,32164,0,1,0.05,0.95,1,AA
278,0,0,0,0,0,0,0,1,0.05,0.95,1,AA

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,1,0,0.95,0.05,1,NaN
1,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
2,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
3,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
4,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
...,...,...,...,...,...,...,...,...,...,...,...,...
364,1,34928,34930,34947,34985,34951,0,1,0.05,0.95,1,AA
365,1,35006,35007,35026,35030,0,1,0,0.05,0.95,0,Ab
366,1,35092,35093,35117,35148,35120,0,1,0.05,0.95,1,aB
367,1,35187,35188,35204,35241,35207,0,1,0.05,0.95,1,AA
368,0,0,0,0,0,0,0,1,0.05,0.95,1,AA

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,0,1,0.95,0.05,0,NaN
1,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
2,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
3,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
4,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
...,...,...,...,...,...,...,...,...,...,...,...,...
172,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
173,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
174,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
175,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
176,0,0,0,0,0,0,0,1,0.05,0.95,0,Aa

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,1,0,0.05,0.95,0,NaN
1,0,0,0,0,0,0,0,1,0.05,0.95,1,aB
2,0,0,0,0,0,0,0,1,0.05,0.95,1,AA
3,1,1295,1296,1322,1460,1325,0,1,0.05,0.95,1,AA
4,1,1600,1602,1625,1634,0,1,0,0.05,0.95,0,Ab
...,...,...,...,...,...,...,...,...,...,...,...,...
203,0,0,0,0,0,0,0,1,0.95,0.05,0,Ab
204,0,0,0,0,0,0,1,0,0.95,0.05,1,aB
205,0,0,0,0,0,0,0,1,0.95,0.05,0,Ab
206,0,0,0,0,0,0,0,1,0.95,0.05,0,aa
207,0,0,0,0,0,0,1,0,0.95,0.05,1,aB

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,1,0,0.05,0.95,1,NaN
1,0,0,0,0,0,0,1,0,0.05,0.95,0,Aa
2,0,0,0,0,0,0,0,1,0.05,0.95,1,aB
3,0,0,0,0,0,0,1,0,0.05,0.95,0,Ab
4,0,0,0,0,0,0,1,0,0.05,0.95,0,aa
...,...,...,...,...,...,...,...,...,...,...,...,...
247,1,43215,43217,43254,43322,43258,0,1,0.05,0.95,1,AA
248,1,43363,43364,43406,43457,43409,0,1,0.05,0.95,1,AA
249,1,43555,43561,43619,43695,43622,0,1,0.05,0.95,1,AA
250,1,43768,43773,43811,43858,43816,0,1,0.05,0.95,1,AA
251,1,43959,43962,43996,44048,43999,0,1,0.05,0.95,1,AA

,hasAllPhotometryData,photometryCenterInIndex,photometryCenterOutIndex,photometrySideInIndex,photometrySideOutIndex,photometryFirstLickIndex,choseLeft,choseRight,leftRewardProb,rightRewardProb,wasRewarded,word
0,0,0,0,0,0,0,0,1,0.95,0.05,0,NaN
1,0,0,0,0,0,0,1,0,0.95,0.05,1,aB
2,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
3,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
4,0,0,0,0,0,0,1,0,0.95,0.05,1,AA
...,...,...,...,...,...,...,...,...,...,...,...,...
258,1,33975,33976,34003,34008,0,0,1,0.05,0.95,0,Aa
259,1,34127,34128,34161,34200,34166,0,1,0.05,0.95,1,aA
260,1,34454,34457,34539,34602,34543,0,1,0.05,0.95,1,AA
261,1,34668,34671,34727,34743,0,1,0,0.05,0.95,0,Ab
262,0,0,0,0,0,0,1,0,0.05,0.95,0,aa

In [12]:
from pathlib import Path
session_infos = [Path(_).parts[-1].replace('.txt', '').split('_')[-2:] for _ in fn_lst if 'SIGNALS' in _]

In [13]:
set([_[0] for _ in session_infos]), set([_[1] for _ in session_infos])

({'S1299', 'S1300', 'S1301', 'S1302'}, {'01312022', '02022022', '02072022'})